# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='co2',
            options={'verbose_name': 'CO2', 'verbose_name_plural': 'CO2s'},
        ),
    ]
